export {
  CLAIM_NATURE_BASE,
  DECISIVE_LEADER_SHARE,
  EVIDENCE_NEGATIVE_FLOOR,
  EVIDENCE_POSITIVE_CAP,
  EVIDENCE_UNIT_MULTIPLIER,
  PENALTY_FALLACY_CAP,
  PENALTY_PER_FALLACY,
  PENALTY_UNSUPPORTED,
  RELATION_CREDIT,
  RELATION_REBUTTAL_BONUS,
  RELEVANCE_WEIGHT,
  SCORE_MAX_CLAIMS,
  SCORE_MAX_EVIDENCE,
  SCORE_MAX_RELATIONS,
  UNDERCUT_PENALTY,
  VERIFICATION_WEIGHT,
} from "@/lib/score/constants";

export {
  accumulateEvidenceShares,
  claimPenalties,
  computeDebateScore,
  evidenceUnit,
  normalizeSpeakerScores,
  scoreClaim,
  toDebateScorePayload,
  type ClaimScoreBreakdown,
  type DebateScoreBreakdown,
  type DebateScoreResult,
  type EvidenceScoreBreakdown,
  type RelationScoreBreakdown,
  type ScoreLeader,
} from "@/lib/score/debateScore";
